export const MAX_CHAT_QUESTION_CHARACTERS = 4_000;
export const MAX_CHAT_REQUEST_BYTES = 32 * 1024;
export const MAX_CHAT_COMPLETION_TOKENS = 4_096;
export const MAX_ROUTING_COMPLETION_TOKENS = 512;
export const MAX_SUMMARY_COMPLETION_TOKENS = 4_096;
